### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sikmir** [odict/odict#9]
I'm trying to build odict:
```sh
$ buck build :odict
...
BUILD FAILED: No build file at BUCK when resolving target //:odict.
```

**Comment by Nickersoft** [comment]
Hey @sikmir,

To be honest, this repo is very out of date! We're in the process of rewriting ODict in GoLang (under the `nickersoft/go` branch) and was not expecting too many people to try using this library just yet 😄 With the Go release we'll be updating our README too. So right now you should be able to compile our WIP Go port from the `nickersoft/go` branch by running:

```
$ go install
$ go build
```

and running the `/.odict` executable.  Just make sure you have Go installed!

**Comment by sikmir** [comment]
Go-based v1.0 is out, `go build` works just fine.

**Comment by sikmir** [comment]
@Nickersoft Just in case, what is odict license?

**Comment by Nickersoft** [comment]
@sikmir Just added one... GNU Public
